server:
  port: 8081

sso:
  server-url: http://localhost:8080/tengo-sso-server
  client-id: web-client

#spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8080