server:
  port: 8081

spring:
  application:
    name: tengo-client

client:
  tengo:
    sso:
      server-url: http://localhost:8080/tengo-sso-server

logging:
  level:
    com.tengo: DEBUG
    org.springframework.security: WARN
